
<?php
// add data from 10/28/2008 staff directory data

$depts = array(
"Adelson Library" => 101,
"Africana Library" => 102,
"Annex Library" => 103,
"Asia Collections" => 111,
"CISER" => 105,
"Coll. Ref. Instr. & Outreach" => 130,
"Digital Libraries & Info Tech" => 131,
"Echols SE Asia Collection" => 115,
"Engineering Library" => 106,
"Fine Arts Library" => 107,
"Geneva Library" => 108,
"Hotel School Library" => 109,
"ILR Catherwood Library" => 110,
"Interlibrary Services" => 141,
"Law Library" => 117,
"Lib Administration" => 136,
"Lib Administrative Operations" => 134,
"Library Alumni Affairs and Development" => 142,
"Library Communications" => 135,
"Library Research" => 140,
"LTS - Acquisitions" => 129,
"LTS - Administration" => 143,
"LTS - Cataloging" => 114,
"LTS - Database Management Services" => 138,
"LTS - EResources & Serials (C)" => 124,
"LTS - EResources & Serials (E)" => 126,
"LTS - Metadata Services" => 139,
"Management Library" => 118,
"Mann Library" => 120,
"Mann Library, Admin" => 123,
"Mann Library, Coll Dev" => 122,
"Mann Library, ITS" => 121,
"Mann Library, Public Serv" => 119,
"Mann Library, Tech Serv" => 125,
"Math Library" => 127,
"Music Library" => 128,
"OKU Access Services" => 137,
"Physical Sciences Library" => 144,
"Preservation & Collection Maintenance (C)" => 133,
"Preservation & Collection Maintenance (P)" => 104,
"Public Services & Assessment" => 132,
"Rare & Manuscript Collections" => 113,
"South Asia Collection" => 112,
"Veterinary Library" => 145,
"Wason E. Asia Collection" => 116
);

// CISER is not listed as a unit library in the Web site
// Entomology does not exist in the staff directory data
$libraries = array(
"Adelson Library" => 230,
"Africana Library" => 215,
"Annex Library" => 216,
"CISER" => null,
"Engineering Library" => 163,
"Fine Arts Library" => 218,
"Geneva Library" => 167,
"Hotel Library" => 219,
"ILR" => 187,
"Kroch Library" => 220,
"Law Library" => 222,
"Management Library" => 223,
"Mann Library" => 224,
"Math Library" => 225,
"Music Library" => 231,
"Olin Library" => 165,
"Physical Sciences Library" => 227,
"Uris Library" => 228,
"Veterinary Library" => 229
);


$new_netids = array(
"jcs93",
"ea18",
"sp91",
"snq2",
"lb74",
"jah43",
"sh364",
"mp268",
"tp16",
"pp238",
"cjh8",
"pmb9",
"cec233",
"jpc27",
"alm22",
"mlp57",
"mep4",
"jhp1",
"jms1",
"csv3",
"ceb6",
"eab4",
"brf44",
"wdp4",
"vp22",
"maw6",
"mpf8",
"hak3",
"mls5",
"kcb2",
"ktb4",
"djb4",
"jeh268",
"vn11",
"dws2",
"jhs11",
"smb6",
"mc31",
"sac29",
"jmd44",
"jdd10",
"sbg13",
"hhh2",
"mmh5",
"zvk2",
"lmk8",
"skl2",
"dsl6",
"gtl1",
"pl17",
"cl672",
"rm527",
"cjm267",
"km15",
"blm2",
"mjn3",
"sar3",
"ps39",
"amw3",
"ljy1",
"cea1",
"bb246",
"db10",
"eb89",
"arc3",
"dwc4",
"ld286",
"ee11",
"lf66",
"cmf58",
"ghg4",
"abg82",
"emh57",
"eek2",
"sek38",
"ll31",
"lml3",
"bjm4",
"djm53",
"dkm11",
"mnr1",
"jcp8",
"jwp42",
"elp48",
"kr33",
"cmr12",
"pjs3",
"kaw5",
"xw53",
"cwy3",
"lz14",
"gsb1",
"jc374",
"pgc1",
"jsd26",
"bbe2",
"cf72",
"cmg13",
"jmg32",
"ekh3",
"keh7",
"smh11",
"jmj45",
"paj3",
"wml1",
"twm26",
"njm5",
"mmm72",
"cmo10",
"jmp8",
"lar11",
"ss234",
"et14",
"bfb2",
"akh8",
"maj2",
"sfk23",
"evm26",
"mlr27",
"rls17",
"das10",
"nt243",
"tsr1",
"mra3",
"ca92",
"fbb5",
"bab7",
"dmc8",
"nac26",
"bdc34",
"ksc3",
"rc28",
"tpc2",
"jac244",
"mnc2",
"jc55",
"shc33",
"nld3",
"mhd6",
"med3",
"jad2",
"eee6",
"jaf30",
"ef15",
"amf6",
"emg34",
"nch9",
"kgj2",
"wjk4",
"whk2",
"ek434",
"jtk1",
"bb75",
"ll32",
"gwl1",
"bjl23",
"cml74",
"jam7",
"hlm7",
"lsk24",
"jpk15",
"mao4",
"jp243",
"jmp36",
"hbr1",
"car26",
"ges9",
"jds11",
"gss1",
"lgs1",
"cls3",
"wjt42",
"wft4",
"nmt5",
" tit1",
"jat264",
"ov1",
"jew24",
"fbw4",
"tw44",
"rdw5",
"msw9",
"jrw11",
"epz1",
"jl41",
"swr1",
"nas20",
"ja253",
"bjb57",
"ehf6",
"crp22",
"ls258",
"kcw44",
"ba16",
"aa19",
"sga3",
"maa21",
"pca1",
"mla4",
"ma225",
"koa2",
"bab2",
"dnb8",
"mb327",
"beb1",
"lmb20",
"djb67",
"ab18",
"sdb94",
"clb13",
"gcb2",
"hrb1",
"rlb54",
"jmb7",
"scb5",
"mb72",
"lgb4",
"jb26",
"ytb1",
"kjb82",
"ccc38",
"pnc1",
"mc256",
"mc257",
"ltc1",
"agc24",
"alc28",
"mc17",
"pac8",
"rtc1",
"hc285",
"smc18",
"vac11",
"jrc88",
"mjc12",
"dc60",
"dc276",
"cac2",
"mjc4",
"ama8",
"pd36",
"cd58",
"dd388",
"efe4",
"mre2",
"ab329",
"moe1",
"rge1",
"cmf7",
"paf3",
"jef17",
"jf13",
"kf12",
"rg27",
"sg14",
"jeg256",
"dkg28",
"grg59",
"ag259",
"oh10",
"mh92",
"pmh54",
"sh549",
"ljh2",
"pbh6",
"jah9",
"jh688",
"ah16",
"seh4",
"tlh39",
"ph44",
"smh26",
"mah94",
"kh14",
"tah16",
"jk448",
"wrk1",
"bak24",
"stk22",
"ark3",
"rk16",
"rak2",
"rk14",
" iab3",
"sok1",
"sk795",
"zk10",
"pak37",
"ahk3",
"gsk5",
"dk15",
"lpk32",
"rk436",
"nk31",
"ysk2",
"mk168",
"jfl65",
"cjl10",
"cgl2",
"jdl8",
"mhl10",
"xl49",
"rpl1",
"sl53",
"SJL8",
"fl31",
"cl26",
"pam62",
"tjm33",
"csm4",
"nm86",
"jpm7",
"ebm7",
"pm66",
"mm524",
"lat3",
"am224",
"jm17",
"tkm2",
"dkm26",
"rsm7",
"ym78",
"bm19",
"lm15",
"jm47",
"njm8",
"bjm9",
"mm355",
"mm342",
"edm29",
"fmm1",
"sm89",
"btn3",
"mn234",
"gln1",
"sn18",
"lew14",
"ko29",
"rmp13",
"fcp2",
"ep17",
"ep19",
"ljp3",
"lp14",
"awp4",
"np55",
"jp126",
"lra8",
"yp39",
"lap11",
"zr25",
"krr45",
"jgr25",
"ir33",
"cpr9",
"jsr38",
"oyr1",
"spr47",
"jr399",
"str1",
"dwr4",
"rw15",
"jds367",
"ws36",
"ws36",
"pas6",
"dj13",
"sms8",
"las11",
"rss32",
"css4",
"ks21",
"gs364",
"bls85",
"tbs23",
"hne2",
"es287",
"sws38",
"nss3",
"ajs17",
"lfs2",
"cs18",
"nv19",
"pjs4",
"lms6",
"daf10",
"dct6",
"kt18",
"bmt1",
"bwt1",
"lmk7",
"jat65",
"kmt38",
"wt32",
"tt96",
"mu44",
"udv1",
"jcv44",
"kw33",
"dcw8",
"sw272",
"wtw3",
"jsw73",
"esw3",
"fw11",
"alw3",
"sbw2",
"ww83",
"gsw55",
"jf40",
"ty15",
"yz276",
"st35",
"kh287",
"dbm2",
"map6",
"lrm1",
"ju23",
"ptv1",
"buw1",
"ab829",
"cb16",
"rbc9",
"gwc5",
"ajc5",
"wjc24",
"tkc2",
"dc242",
"ad322",
"te32",
"drf5",
"dlf2",
"jaf46",
"img22",
"ljh5",
"sk274",
"rfk45",
"gm83",
"mdr35",
"ps265",
"bb29",
"aes44",
"kt76",
"cw287",
"eph8",
"tlk23",
"ckl8",
"pem2",
"dmt22",
"skw2"
);

$netids_to_dept = array(
"jcs93" => "Adelson Library",
"ea18" => "Africana Library",
"sp91" => "Africana Library",
"snq2" => "Africana Library",
"lb74" => "Annex Library",
"jah43" => "Annex Library",
"sh364" => "Annex Library",
"mp268" => "Annex Library",
"tp16" => "Preservation & Collection Maintenance (P)",
"pp238" => "Annex Library",
"cjh8" => "Annex Library",
"pmb9" => "CISER",
"cec233" => "Engineering Library",
"jpc27" => "Engineering Library",
"alm22" => "Engineering Library",
"mlp57" => "Engineering Library",
"mep4" => "Engineering Library",
"jhp1" => "Engineering Library",
"jms1" => "Engineering Library",
"csv3" => "Engineering Library",
"ceb6" => "Fine Arts Library",
"eab4" => "Fine Arts Library",
"brf44" => "Fine Arts Library",
"wdp4" => "Fine Arts Library",
"vp22" => "Fine Arts Library",
"maw6" => "Fine Arts Library",
"mpf8" => "Geneva Library",
"hak3" => "Geneva Library",
"mls5" => "Geneva Library",
"kcb2" => "Hotel School Library",
"ktb4" => "Hotel School Library",
"djb4" => "Hotel School Library",
"jeh268" => "Hotel School Library",
"vn11" => "Hotel School Library",
"dws2" => "Hotel School Library",
"jhs11" => "Hotel School Library",
"smb6" => "ILR Catherwood Library",
"mc31" => "ILR Catherwood Library",
"sac29" => "ILR Catherwood Library",
"jmd44" => "ILR Catherwood Library",
"jdd10" => "ILR Catherwood Library",
"sbg13" => "ILR Catherwood Library",
"hhh2" => "ILR Catherwood Library",
"mmh5" => "ILR Catherwood Library",
"zvk2" => "ILR Catherwood Library",
"lmk8" => "ILR Catherwood Library",
"skl2" => "ILR Catherwood Library",
"dsl6" => "ILR Catherwood Library",
"gtl1" => "ILR Catherwood Library",
"pl17" => "ILR Catherwood Library",
"cl672" => "ILR Catherwood Library",
"rm527" => "ILR Catherwood Library",
"cjm267" => "ILR Catherwood Library",
"km15" => "ILR Catherwood Library",
"blm2" => "ILR Catherwood Library",
"mjn3" => "ILR Catherwood Library",
"sar3" => "ILR Catherwood Library",
"ps39" => "ILR Catherwood Library",
"amw3" => "ILR Catherwood Library",
"ljy1" => "ILR Catherwood Library",
"cea1" => "Asia Collections",
"bb246" => "South Asia Collection",
"db10" => "Rare & Manuscript Collections",
"eb89" => "Rare & Manuscript Collections",
"arc3" => "LTS - Cataloging",
"dwc4" => "Rare & Manuscript Collections",
"ld286" => "Echols SE Asia Collection",
"ee11" => "Rare & Manuscript Collections",
"lf66" => "Rare & Manuscript Collections",
"cmf58" => "Rare & Manuscript Collections",
"ghg4" => "Echols SE Asia Collection",
"abg82" => "Rare & Manuscript Collections",
"emh57" => "Rare & Manuscript Collections",
"eek2" => "Rare & Manuscript Collections",
"sek38" => "Rare & Manuscript Collections",
"ll31" => "South Asia Collection",
"lml3" => "Rare & Manuscript Collections",
"bjm4" => "Rare & Manuscript Collections",
"djm53" => "Wason E. Asia Collection",
"dkm11" => "Rare & Manuscript Collections",
"mnr1" => "LTS - Cataloging",
"jcp8" => "Rare & Manuscript Collections",
"jwp42" => "Echols SE Asia Collection",
"elp48" => "Rare & Manuscript Collections",
"kr33" => "Rare & Manuscript Collections",
"cmr12" => "Rare & Manuscript Collections",
"pjs3" => "Rare & Manuscript Collections",
"kaw5" => "Rare & Manuscript Collections",
"xw53" => "Wason E. Asia Collection",
"cwy3" => "Wason E. Asia Collection",
"lz14" => "Wason E. Asia Collection",
"gsb1" => "Law Library",
"jc374" => "Law Library",
"pgc1" => "Law Library",
"jsd26" => "Law Library",
"bbe2" => "Law Library",
"cf72" => "Law Library",
"cmg13" => "Law Library",
"jmg32" => "Law Library",
"ekh3" => "Law Library",
"keh7" => "Law Library",
"smh11" => "Law Library",
"jmj45" => "Law Library",
"paj3" => "Law Library",
"wml1" => "Law Library",
"twm26" => "Law Library",
"njm5" => "Law Library",
"mmm72" => "Law Library",
"cmo10" => "Law Library",
"jmp8" => "Law Library",
"lar11" => "Law Library",
"ss234" => "Law Library",
"et14" => "Law Library",
"bfb2" => "Management Library",
"akh8" => "Management Library",
"maj2" => "Management Library",
"sfk23" => "Management Library",
"evm26" => "Management Library",
"mlr27" => "Management Library",
"rls17" => "Management Library",
"das10" => "Management Library",
"nt243" => "Management Library",
"tsr1" => "Management Library",
"mra3" => "Mann Library, Public Serv",
"ca92" => "Mann Library",
"fbb5" => "Mann Library",
"bab7" => "Mann Library, Public Serv",
"dmc8" => "Mann Library, ITS",
"nac26" => "Mann Library",
"bdc34" => "Mann Library, ITS",
"ksc3" => "Mann Library, Public Serv",
"rc28" => "LTS - Cataloging",
"tpc2" => "Mann Library, Public Serv",
"jac244" => "Mann Library, ITS",
"mnc2" => "Mann Library, Coll Dev",
"jc55" => "Mann Library, ITS",
"shc33" => "Mann Library, Admin",
"nld3" => "Mann Library, Public Serv",
"mhd6" => "Mann Library",
"med3" => "Mann Library, Public Serv",
"jad2" => "Mann Library, Public Serv",
"eee6" => "LTS - EResources & Serials (C)",
"jaf30" => "Mann Library, ITS",
"ef15" => "Mann Library, Admin",
"amf6" => "Mann Library, Admin",
"emg34" => "Mann Library",
"nch9" => "Mann Library, Public Serv",
"kgj2" => "Mann Library",
"wjk4" => "LTS - EResources & Serials (C)",
"whk2" => "Mann Library, ITS",
"ek434" => "Annex Library",
"jtk1" => "Mann Library, Public Serv",
"bb75" => "Mann Library, Public Serv",
"ll32" => "Mann Library",
"gwl1" => "Mann Library, Tech Serv",
"bjl23" => "Mann Library, ITS",
"cml74" => "Mann Library",
"jam7" => "Mann Library, Admin",
"hlm7" => "Mann Library, ITS",
"lsk24" => "LTS - EResources & Serials (C)",
"jpk15" => "Mann Library, Public Serv",
"mao4" => "Mann Library, Coll Dev",
"jp243" => "Mann Library, Coll Dev",
"jmp36" => "Mann Library, Public Serv",
"hbr1" => "Mann Library, Public Serv",
"car26" => "Mann Library, Admin",
"ges9" => "Mann Library, Coll Dev",
"jds11" => "LTS - EResources & Serials (C)",
"gss1" => "Mann Library",
"lgs1" => "Mann Library, Coll Dev",
"cls3" => "LTS - EResources & Serials (C)",
"wjt42" => "Mann Library, Admin",
"wft4" => "Mann Library, Public Serv",
"nmt5" => "LTS - EResources & Serials (E)",
" tit1" => "Mann Library, Public Serv",
"jat264" => "Mann Library, Admin",
"ov1" => "Mann Library, Admin",
"jew24" => "Mann Library, Coll Dev",
"fbw4" => "Mann Library, ITS",
"tw44" => "Mann Library, Public Serv",
"rdw5" => "LTS - EResources & Serials (E)",
"msw9" => "LTS - Cataloging",
"jrw11" => "Mann Library, Public Serv",
"epz1" => "LTS - EResources & Serials (E)",
"jl41" => "Math Library",
"swr1" => "Math Library",
"nas20" => "Math Library",
"ja253" => "LTS - Cataloging",
"bjb57" => "Music Library",
"ehf6" => "Music Library",
"crp22" => "Music Library",
"ls258" => "Music Library",
"kcw44" => "LTS - Cataloging",
"ba16" => "LTS - Acquisitions",
"aa19" => "Coll. Ref. Instr. & Outreach",
"sga3" => "Preservation & Collection Maintenance (P)",
"maa21" => "Digital Libraries & Info Tech",
"pca1" => "LTS - Cataloging",
"mla4" => "Public Services & Assessment",
"ma225" => "LTS - Acquisitions",
"koa2" => "Preservation & Collection Maintenance (C)",
"bab2" => "Lib Administrative Operations",
"dnb8" => "LTS - Cataloging",
"mb327" => "Digital Libraries & Info Tech",
"beb1" => "Preservation & Collection Maintenance (P)",
"lmb20" => "Library Communications",
"djb67" => "Digital Libraries & Info Tech",
"ab18" => "Digital Libraries & Info Tech",
"sdb94" => "Digital Libraries & Info Tech",
"clb13" => "Lib Administrative Operations",
"gcb2" => "LTS - Acquisitions",
"hrb1" => "Coll. Ref. Instr. & Outreach",
"rlb54" => "Lib Administration",
"jmb7" => "Preservation & Collection Maintenance (P)",
"scb5" => "Lib Administrative Operations",
"mb72" => "Preservation & Collection Maintenance (P)",
"lgb4" => "Lib Administrative Operations",
"jb26" => "LTS - Acquisitions",
"ytb1" => "LTS - Cataloging",
"kjb82" => "Coll. Ref. Instr. & Outreach",
"ccc38" => "Lib Administrative Operations",
"pnc1" => "Coll. Ref. Instr. & Outreach",
"mc256" => "LTS - Cataloging",
"mc257" => "Preservation & Collection Maintenance (C)",
"ltc1" => "Lib Administration",
"agc24" => "Coll. Ref. Instr. & Outreach",
"alc28" => "LTS - EResources & Serials (C)",
"mc17" => "LTS - Cataloging",
"pac8" => "Preservation & Collection Maintenance (P)",
"rtc1" => "Preservation & Collection Maintenance (P)",
"hc285" => "Preservation & Collection Maintenance (C)",
"smc18" => "Preservation & Collection Maintenance (P)",
"vac11" => "Coll. Ref. Instr. & Outreach",
"jrc88" => "Library Communications",
"mjc12" => "Digital Libraries & Info Tech",
"dc60" => "Preservation & Collection Maintenance (C)",
"dc276" => "OKU Access Services",
"cac2" => "LTS - Database Management Services",
"mjc4" => "Lib Administration",
"ama8" => "Lib Administrative Operations",
"pd36" => "LTS - Cataloging",
"cd58" => "Library Communications",
"dd388" => "LTS - Metadata Services",
"efe4" => "Rare & Manuscript Collections",
"mre2" => "Lib Administration",
"ab329" => "Preservation & Collection Maintenance (P)",
"moe1" => "Coll. Ref. Instr. & Outreach",
"rge1" => "Library Research",
"cmf7" => "Interlibrary Services",
"paf3" => "Preservation & Collection Maintenance (P)",
"jef17" => "Preservation & Collection Maintenance (C)",
"jf13" => "LTS - Database Management Services",
"kf12" => "LTS - Cataloging",
"rg27" => "Digital Libraries & Info Tech",
"sg14" => "Digital Libraries & Info Tech",
"jeg256" => "OKU Access Services",
"dkg28" => "Preservation & Collection Maintenance (P)",
"grg59" => "Library Communications",
"ag259" => "Digital Libraries & Info Tech",
"oh10" => "Digital Libraries & Info Tech",
"mh92" => "Preservation & Collection Maintenance (P)",
"pmh54" => "Interlibrary Services",
"sh549" => "LTS - Cataloging",
"ljh2" => "Digital Libraries & Info Tech",
"pbh6" => "Public Services & Assessment",
"jah9" => "Lib Administrative Operations",
"jh688" => "Digital Libraries & Info Tech",
"ah16" => "LTS - Cataloging",
"seh4" => "Coll. Ref. Instr. & Outreach",
"tlh39" => "Lib Administration",
"ph44" => "Digital Libraries & Info Tech",
"smh26" => "Preservation & Collection Maintenance (P)",
"mah94" => "OKU Access Services",
"kh14" => "Preservation & Collection Maintenance (C)",
"tah16" => "Preservation & Collection Maintenance (C)",
"jk448" => "OKU Access Services",
"wrk1" => "Digital Libraries & Info Tech",
"bak24" => "LTS - Cataloging",
"stk22" => "Library Alumni Affairs and Development",
"ark3" => "Lib Administration",
"rk16" => "Coll. Ref. Instr. & Outreach",
"rak2" => "Interlibrary Services",
"rk14" => "Preservation & Collection Maintenance (C)",
" iab3" => "Preservation & Collection Maintenance (P)",
"sok1" => "LTS - Cataloging",
"sk795" => "Lib Administration",
"zk10" => "Lib Administration",
"pak37" => "Lib Administrative Operations",
"ahk3" => "LTS - Acquisitions",
"gsk5" => "Digital Libraries & Info Tech",
"dk15" => "Lib Administration",
"lpk32" => "Digital Libraries & Info Tech",
"rk436" => "Coll. Ref. Instr. & Outreach",
"nk31" => "LTS - Acquisitions",
"ysk2" => "LTS - Cataloging",
"mk168" => "Digital Libraries & Info Tech",
"jfl65" => "Lib Administrative Operations",
"cjl10" => "Library Communications",
"cgl2" => "LTS - Cataloging",
"jdl8" => "LTS - Acquisitions",
"mhl10" => "Digital Libraries & Info Tech",
"xl49" => "Public Services & Assessment",
"rpl1" => "Digital Libraries & Info Tech",
"sl53" => "LTS - Acquisitions",
"SJL8" => "LTS - Database Management Services",
"fl31" => "LTS - Cataloging",
"cl26" => "LTS - Acquisitions",
"pam62" => "Digital Libraries & Info Tech",
"tjm33" => "Lib Administrative Operations",
"csm4" => "OKU Access Services",
"nm86" => "Coll. Ref. Instr. & Outreach",
"jpm7" => "Preservation & Collection Maintenance (C)",
"ebm7" => "Library Communications",
"pm66" => "LTS - Database Management Services",
"mm524" => "Digital Libraries & Info Tech",
"lat3" => "LTS - Acquisitions",
"am224" => "LTS - Cataloging",
"jm17" => "LTS - Database Management Services",
"tkm2" => "LTS - Cataloging",
"dkm26" => "Digital Libraries & Info Tech",
"rsm7" => "Preservation & Collection Maintenance (C)",
"ym78" => "LTS - Acquisitions",
"bm19" => "Preservation & Collection Maintenance (C)",
"lm15" => "Library Research",
"jm47" => "Interlibrary Services",
"njm8" => "Preservation & Collection Maintenance (C)",
"bjm9" => "Digital Libraries & Info Tech",
"mm355" => "LTS - Acquisitions",
"mm342" => "Coll. Ref. Instr. & Outreach",
"edm29" => "LTS - Cataloging",
"fmm1" => "Coll. Ref. Instr. & Outreach",
"sm89" => "LTS - Cataloging",
"btn3" => "LTS - Acquisitions",
"mn234" => "OKU Access Services",
"gln1" => "LTS - Metadata Services",
"sn18" => "Coll. Ref. Instr. & Outreach",
"lew14" => "Coll. Ref. Instr. & Outreach",
"ko29" => "Interlibrary Services",
"rmp13" => "Preservation & Collection Maintenance (C)",
"fcp2" => "Digital Libraries & Info Tech",
"ep17" => "LTS - EResources & Serials (E)",
"ep19" => "LTS - Cataloging",
"ljp3" => "LTS - EResources & Serials (E)",
"lp14" => "Digital Libraries & Info Tech",
"awp4" => "Lib Administrative Operations",
"np55" => "LTS - Database Management Services",
"jp126" => "Public Services & Assessment",
"lra8" => "Lib Administrative Operations",
"yp39" => "Preservation & Collection Maintenance (C)",
"lap11" => "LTS - Cataloging",
"zr25" => "Preservation & Collection Maintenance (P)",
"krr45" => "Lib Administration",
"jgr25" => "Digital Libraries & Info Tech",
"ir33" => "Public Services & Assessment",
"cpr9" => "LTS - Cataloging",
"jsr38" => "Digital Libraries & Info Tech",
"oyr1" => "Digital Libraries & Info Tech",
"spr47" => "Digital Libraries & Info Tech",
"jr399" => "Digital Libraries & Info Tech",
"str1" => "LTS - Cataloging",
"dwr4" => "Digital Libraries & Info Tech",
"rw15" => "LTS - EResources & Serials (E)",
"jds367" => "Lib Administration",
"ws36" => "Coll. Ref. Instr. & Outreach",
"ws36" => "LTS - Acquisitions",
"pas6" => "Public Services & Assessment",
"dj13" => "Coll. Ref. Instr. & Outreach",
"sms8" => "Preservation & Collection Maintenance (C)",
"las11" => "Lib Administrative Operations",
"rss32" => "Lib Administrative Operations",
"css4" => "LTS - Cataloging",
"ks21" => "Preservation & Collection Maintenance (C)",
"gs364" => "Digital Libraries & Info Tech",
"bls85" => "OKU Access Services",
"tbs23" => "OKU Access Services",
"hne2" => "LTS - Cataloging",
"es287" => "Digital Libraries & Info Tech",
"sws38" => "LTS - Acquisitions",
"nss3" => "Coll. Ref. Instr. & Outreach",
"ajs17" => "Digital Libraries & Info Tech",
"lfs2" => "Preservation & Collection Maintenance (P)",
"cs18" => "LTS - EResources & Serials (E)",
"nv19" => "LTS - Metadata Services",
"pjs4" => "LTS - Cataloging",
"lms6" => "LTS - Cataloging",
"daf10" => "LTS - Cataloging",
"dct6" => "LTS - Database Management Services",
"kt18" => "Coll. Ref. Instr. & Outreach",
"bmt1" => "LTS - Database Management Services",
"bwt1" => "LTS - Cataloging",
"lmk7" => "Coll. Ref. Instr. & Outreach",
"jat65" => "Interlibrary Services",
"kmt38" => "LTS - Database Management Services",
"wt32" => "LTS - Database Management Services",
"tt96" => "LTS - Acquisitions",
"mu44" => "LTS - Acquisitions",
"udv1" => "Preservation & Collection Maintenance (C)",
"jcv44" => "Preservation & Collection Maintenance (C)",
"kw33" => "Coll. Ref. Instr. & Outreach",
"dcw8" => "LTS - Database Management Services",
"sw272" => "Digital Libraries & Info Tech",
"wtw3" => "Coll. Ref. Instr. & Outreach",
"jsw73" => "Digital Libraries & Info Tech",
"esw3" => "Lib Administration",
"fw11" => "LTS - Database Management Services",
"alw3" => "LTS - Cataloging",
"sbw2" => "LTS - Administration",
"ww83" => "Coll. Ref. Instr. & Outreach",
"gsw55" => "LTS - Metadata Services",
"jf40" => "OKU Access Services",
"ty15" => "LTS - Acquisitions",
"yz276" => "LTS - Acquisitions",
"st35" => "Physical Sciences Library",
"kh287" => "Physical Sciences Library",
"dbm2" => "Physical Sciences Library",
"map6" => "Physical Sciences Library",
"lrm1" => "Physical Sciences Library",
"ju23" => "Physical Sciences Library",
"ptv1" => "Physical Sciences Library",
"buw1" => "Physical Sciences Library",
"ab829" => "OKU Access Services",
"cb16" => "OKU Access Services",
"rbc9" => "Lib Administrative Operations",
"gwc5" => "Lib Administrative Operations",
"ajc5" => "Coll. Ref. Instr. & Outreach",
"wjc24" => "OKU Access Services",
"tkc2" => "Lib Administrative Operations",
"dc242" => "OKU Access Services",
"ad322" => "OKU Access Services",
"te32" => "Digital Libraries & Info Tech",
"drf5" => "Lib Administrative Operations",
"dlf2" => "Digital Libraries & Info Tech",
"jaf46" => "OKU Access Services",
"img22" => "Lib Administrative Operations",
"ljh5" => "Coll. Ref. Instr. & Outreach",
"sk274" => "Digital Libraries & Info Tech",
"rfk45" => "OKU Access Services",
"gm83" => "OKU Access Services",
"mdr35" => "Lib Administrative Operations",
"ps265" => "Lib Administrative Operations",
"bb29" => "OKU Access Services",
"aes44" => "Lib Administrative Operations",
"kt76" => "OKU Access Services",
"cw287" => "OKU Access Services",
"eph8" => "Veterinary Library",
"tlk23" => "Veterinary Library",
"ckl8" => "Veterinary Library",
"pem2" => "Veterinary Library",
"dmt22" => "Veterinary Library",
"skw2" => "Veterinary Library"
);

$netids_to_library = array(
"jcs93" => "Adelson Library",
"ea18" => "Africana Library",
"sp91" => "Africana Library",
"snq2" => "Africana Library",
"lb74" => "Annex Library",
"jah43" => "Annex Library",
"sh364" => "Annex Library",
"mp268" => "Annex Library",
"tp16" => "Annex Library",
"pp238" => "Annex Library",
"cjh8" => "Annex Library",
"pmb9" => "CISER",
"cec233" => "Engineering Library",
"jpc27" => "Engineering Library",
"alm22" => "Engineering Library",
"mlp57" => "Engineering Library",
"mep4" => "Engineering Library",
"jhp1" => "Engineering Library",
"jms1" => "Engineering Library",
"csv3" => "Engineering Library",
"ceb6" => "Fine Arts Library",
"eab4" => "Fine Arts Library",
"brf44" => "Fine Arts Library",
"wdp4" => "Fine Arts Library",
"vp22" => "Fine Arts Library",
"maw6" => "Fine Arts Library",
"mpf8" => "Geneva Library",
"hak3" => "Geneva Library",
"mls5" => "Geneva Library",
"kcb2" => "Hotel Library",
"ktb4" => "Hotel Library",
"djb4" => "Hotel Library",
"jeh268" => "Hotel Library",
"vn11" => "Hotel Library",
"dws2" => "Hotel Library",
"jhs11" => "Hotel Library",
"smb6" => "ILR",
"mc31" => "ILR",
"sac29" => "ILR",
"jmd44" => "ILR",
"jdd10" => "ILR",
"sbg13" => "ILR",
"hhh2" => "ILR",
"mmh5" => "ILR",
"zvk2" => "ILR",
"lmk8" => "ILR",
"skl2" => "ILR",
"dsl6" => "ILR",
"gtl1" => "ILR",
"pl17" => "ILR",
"cl672" => "ILR",
"rm527" => "ILR",
"cjm267" => "ILR",
"km15" => "ILR",
"blm2" => "ILR",
"mjn3" => "ILR",
"sar3" => "ILR",
"ps39" => "ILR",
"amw3" => "ILR",
"ljy1" => "ILR",
"cea1" => "Kroch Library",
"bb246" => "Kroch Library",
"db10" => "Kroch Library",
"eb89" => "Kroch Library",
"arc3" => "Kroch Library",
"dwc4" => "Kroch Library",
"ld286" => "Kroch Library",
"ee11" => "Kroch Library",
"lf66" => "Kroch Library",
"cmf58" => "Kroch Library",
"ghg4" => "Kroch Library",
"abg82" => "Kroch Library",
"emh57" => "Kroch Library",
"eek2" => "Kroch Library",
"sek38" => "Kroch Library",
"ll31" => "Kroch Library",
"lml3" => "Kroch Library",
"bjm4" => "Kroch Library",
"djm53" => "Kroch Library",
"dkm11" => "Kroch Library",
"mnr1" => "Kroch Library",
"jcp8" => "Kroch Library",
"jwp42" => "Kroch Library",
"elp48" => "Kroch Library",
"kr33" => "Kroch Library",
"cmr12" => "Kroch Library",
"pjs3" => "Kroch Library",
"kaw5" => "Kroch Library",
"xw53" => "Kroch Library",
"cwy3" => "Kroch Library",
"lz14" => "Kroch Library",
"gsb1" => "Law Library",
"jc374" => "Law Library",
"pgc1" => "Law Library",
"jsd26" => "Law Library",
"bbe2" => "Law Library",
"cf72" => "Law Library",
"cmg13" => "Law Library",
"jmg32" => "Law Library",
"ekh3" => "Law Library",
"keh7" => "Law Library",
"smh11" => "Law Library",
"jmj45" => "Law Library",
"paj3" => "Law Library",
"wml1" => "Law Library",
"twm26" => "Law Library",
"njm5" => "Law Library",
"mmm72" => "Law Library",
"cmo10" => "Law Library",
"jmp8" => "Law Library",
"lar11" => "Law Library",
"ss234" => "Law Library",
"et14" => "Law Library",
"bfb2" => "Management Library",
"akh8" => "Management Library",
"maj2" => "Management Library",
"sfk23" => "Management Library",
"evm26" => "Management Library",
"mlr27" => "Management Library",
"rls17" => "Management Library",
"das10" => "Management Library",
"nt243" => "Management Library",
"tsr1" => "Management Library",
"mra3" => "Mann Library",
"ca92" => "Mann Library",
"fbb5" => "Mann Library",
"bab7" => "Mann Library",
"dmc8" => "Mann Library",
"nac26" => "Mann Library",
"bdc34" => "Mann Library",
"ksc3" => "Mann Library",
"rc28" => "Mann Library",
"tpc2" => "Mann Library",
"jac244" => "Mann Library",
"mnc2" => "Mann Library",
"jc55" => "Mann Library",
"shc33" => "Mann Library",
"nld3" => "Mann Library",
"mhd6" => "Mann Library",
"med3" => "Mann Library",
"jad2" => "Mann Library",
"eee6" => "Mann Library",
"jaf30" => "Mann Library",
"ef15" => "Mann Library",
"amf6" => "Mann Library",
"emg34" => "Mann Library",
"nch9" => "Mann Library",
"kgj2" => "Mann Library",
"wjk4" => "Mann Library",
"whk2" => "Mann Library",
"ek434" => "Mann Library",
"jtk1" => "Mann Library",
"bb75" => "Mann Library",
"ll32" => "Mann Library",
"gwl1" => "Mann Library",
"bjl23" => "Mann Library",
"cml74" => "Mann Library",
"jam7" => "Mann Library",
"hlm7" => "Mann Library",
"lsk24" => "Mann Library",
"jpk15" => "Mann Library",
"mao4" => "Mann Library",
"jp243" => "Mann Library",
"jmp36" => "Mann Library",
"hbr1" => "Mann Library",
"car26" => "Mann Library",
"ges9" => "Mann Library",
"jds11" => "Mann Library",
"gss1" => "Mann Library",
"lgs1" => "Mann Library",
"cls3" => "Mann Library",
"wjt42" => "Mann Library",
"wft4" => "Mann Library",
"nmt5" => "Mann Library",
" tit1" => "Mann Library",
"jat264" => "Mann Library",
"ov1" => "Mann Library",
"jew24" => "Mann Library",
"fbw4" => "Mann Library",
"tw44" => "Mann Library",
"rdw5" => "Mann Library",
"msw9" => "Mann Library",
"jrw11" => "Mann Library",
"epz1" => "Mann Library",
"jl41" => "Math Library",
"swr1" => "Math Library",
"nas20" => "Math Library",
"ja253" => "Music Library",
"bjb57" => "Music Library",
"ehf6" => "Music Library",
"crp22" => "Music Library",
"ls258" => "Music Library",
"kcw44" => "Music Library",
"ba16" => "Olin Library",
"aa19" => "Olin Library",
"sga3" => "Olin Library",
"maa21" => "Olin Library",
"pca1" => "Olin Library",
"mla4" => "Olin Library",
"ma225" => "Olin Library",
"koa2" => "Olin Library",
"bab2" => "Olin Library",
"dnb8" => "Olin Library",
"mb327" => "Olin Library",
"beb1" => "Olin Library",
"lmb20" => "Olin Library",
"djb67" => "Olin Library",
"ab18" => "Olin Library",
"sdb94" => "Olin Library",
"clb13" => "Olin Library",
"gcb2" => "Olin Library",
"hrb1" => "Olin Library",
"rlb54" => "Olin Library",
"jmb7" => "Olin Library",
"scb5" => "Olin Library",
"mb72" => "Olin Library",
"lgb4" => "Olin Library",
"jb26" => "Olin Library",
"ytb1" => "Olin Library",
"kjb82" => "Olin Library",
"ccc38" => "Olin Library",
"pnc1" => "Olin Library",
"mc256" => "Olin Library",
"mc257" => "Olin Library",
"ltc1" => "Olin Library",
"agc24" => "Olin Library",
"alc28" => "Olin Library",
"mc17" => "Olin Library",
"pac8" => "Olin Library",
"rtc1" => "Olin Library",
"hc285" => "Olin Library",
"smc18" => "Olin Library",
"vac11" => "Olin Library",
"jrc88" => "Olin Library",
"mjc12" => "Olin Library",
"dc60" => "Olin Library",
"dc276" => "Olin Library",
"cac2" => "Olin Library",
"mjc4" => "Olin Library",
"ama8" => "Olin Library",
"pd36" => "Olin Library",
"cd58" => "Olin Library",
"dd388" => "Olin Library",
"efe4" => "Olin Library",
"mre2" => "Olin Library",
"ab329" => "Olin Library",
"moe1" => "Olin Library",
"rge1" => "Olin Library",
"cmf7" => "Olin Library",
"paf3" => "Olin Library",
"jef17" => "Olin Library",
"jf13" => "Olin Library",
"kf12" => "Olin Library",
"rg27" => "Olin Library",
"sg14" => "Olin Library",
"jeg256" => "Olin Library",
"dkg28" => "Olin Library",
"grg59" => "Olin Library",
"ag259" => "Olin Library",
"oh10" => "Olin Library",
"mh92" => "Olin Library",
"pmh54" => "Olin Library",
"sh549" => "Olin Library",
"ljh2" => "Olin Library",
"pbh6" => "Olin Library",
"jah9" => "Olin Library",
"jh688" => "Olin Library",
"ah16" => "Olin Library",
"seh4" => "Olin Library",
"tlh39" => "Olin Library",
"ph44" => "Olin Library",
"smh26" => "Olin Library",
"mah94" => "Olin Library",
"kh14" => "Olin Library",
"tah16" => "Olin Library",
"jk448" => "Olin Library",
"wrk1" => "Olin Library",
"bak24" => "Olin Library",
"stk22" => "Olin Library",
"ark3" => "Olin Library",
"rk16" => "Olin Library",
"rak2" => "Olin Library",
"rk14" => "Olin Library",
" iab3" => "Olin Library",
"sok1" => "Olin Library",
"sk795" => "Olin Library",
"zk10" => "Olin Library",
"pak37" => "Olin Library",
"ahk3" => "Olin Library",
"gsk5" => "Olin Library",
"dk15" => "Olin Library",
"lpk32" => "Olin Library",
"rk436" => "Olin Library",
"nk31" => "Olin Library",
"ysk2" => "Olin Library",
"mk168" => "Olin Library",
"jfl65" => "Olin Library",
"cjl10" => "Olin Library",
"cgl2" => "Olin Library",
"jdl8" => "Olin Library",
"mhl10" => "Olin Library",
"xl49" => "Olin Library",
"rpl1" => "Olin Library",
"sl53" => "Olin Library",
"SJL8" => "Olin Library",
"fl31" => "Olin Library",
"cl26" => "Olin Library",
"pam62" => "Olin Library",
"tjm33" => "Olin Library",
"csm4" => "Olin Library",
"nm86" => "Olin Library",
"jpm7" => "Olin Library",
"ebm7" => "Olin Library",
"pm66" => "Olin Library",
"mm524" => "Olin Library",
"lat3" => "Olin Library",
"am224" => "Olin Library",
"jm17" => "Olin Library",
"tkm2" => "Olin Library",
"dkm26" => "Olin Library",
"rsm7" => "Olin Library",
"ym78" => "Olin Library",
"bm19" => "Olin Library",
"lm15" => "Olin Library",
"jm47" => "Olin Library",
"njm8" => "Olin Library",
"bjm9" => "Olin Library",
"mm355" => "Olin Library",
"mm342" => "Olin Library",
"edm29" => "Olin Library",
"fmm1" => "Olin Library",
"sm89" => "Olin Library",
"btn3" => "Olin Library",
"mn234" => "Olin Library",
"gln1" => "Olin Library",
"sn18" => "Olin Library",
"lew14" => "Olin Library",
"ko29" => "Olin Library",
"rmp13" => "Olin Library",
"fcp2" => "Olin Library",
"ep17" => "Olin Library",
"ep19" => "Olin Library",
"ljp3" => "Olin Library",
"lp14" => "Olin Library",
"awp4" => "Olin Library",
"np55" => "Olin Library",
"jp126" => "Olin Library",
"lra8" => "Olin Library",
"yp39" => "Olin Library",
"lap11" => "Olin Library",
"zr25" => "Olin Library",
"krr45" => "Olin Library",
"jgr25" => "Olin Library",
"ir33" => "Olin Library",
"cpr9" => "Olin Library",
"jsr38" => "Olin Library",
"oyr1" => "Olin Library",
"spr47" => "Olin Library",
"jr399" => "Olin Library",
"str1" => "Olin Library",
"dwr4" => "Olin Library",
"rw15" => "Olin Library",
"jds367" => "Olin Library",
"ws36" => "Olin Library",
"ws36" => "Olin Library",
"pas6" => "Olin Library",
"dj13" => "Olin Library",
"sms8" => "Olin Library",
"las11" => "Olin Library",
"rss32" => "Olin Library",
"css4" => "Olin Library",
"ks21" => "Olin Library",
"gs364" => "Olin Library",
"bls85" => "Olin Library",
"tbs23" => "Olin Library",
"hne2" => "Olin Library",
"es287" => "Olin Library",
"sws38" => "Olin Library",
"nss3" => "Olin Library",
"ajs17" => "Olin Library",
"lfs2" => "Olin Library",
"cs18" => "Olin Library",
"nv19" => "Olin Library",
"pjs4" => "Olin Library",
"lms6" => "Olin Library",
"daf10" => "Olin Library",
"dct6" => "Olin Library",
"kt18" => "Olin Library",
"bmt1" => "Olin Library",
"bwt1" => "Olin Library",
"lmk7" => "Olin Library",
"jat65" => "Olin Library",
"kmt38" => "Olin Library",
"wt32" => "Olin Library",
"tt96" => "Olin Library",
"mu44" => "Olin Library",
"udv1" => "Olin Library",
"jcv44" => "Olin Library",
"kw33" => "Olin Library",
"dcw8" => "Olin Library",
"sw272" => "Olin Library",
"wtw3" => "Olin Library",
"jsw73" => "Olin Library",
"esw3" => "Olin Library",
"fw11" => "Olin Library",
"alw3" => "Olin Library",
"sbw2" => "Olin Library",
"ww83" => "Olin Library",
"gsw55" => "Olin Library",
"jf40" => "Olin Library",
"ty15" => "Olin Library",
"yz276" => "Olin Library",
"st35" => "Physical Sciences Library",
"kh287" => "Physical Sciences Library",
"dbm2" => "Physical Sciences Library",
"map6" => "Physical Sciences Library",
"lrm1" => "Physical Sciences Library",
"ju23" => "Physical Sciences Library",
"ptv1" => "Physical Sciences Library",
"buw1" => "Physical Sciences Library",
"ab829" => "Uris Library",
"cb16" => "Uris Library",
"rbc9" => "Uris Library",
"gwc5" => "Uris Library",
"ajc5" => "Uris Library",
"wjc24" => "Uris Library",
"tkc2" => "Uris Library",
"dc242" => "Uris Library",
"ad322" => "Uris Library",
"te32" => "Uris Library",
"drf5" => "Uris Library",
"dlf2" => "Uris Library",
"jaf46" => "Uris Library",
"img22" => "Uris Library",
"ljh5" => "Uris Library",
"sk274" => "Uris Library",
"rfk45" => "Uris Library",
"gm83" => "Uris Library",
"mdr35" => "Uris Library",
"ps265" => "Uris Library",
"bb29" => "Uris Library",
"aes44" => "Uris Library",
"kt76" => "Uris Library",
"cw287" => "Uris Library",
"eph8" => "Veterinary Library",
"tlk23" => "Veterinary Library",
"ckl8" => "Veterinary Library",
"pem2" => "Veterinary Library",
"dmt22" => "Veterinary Library",
"skw2" => "Veterinary Library"
);

error_reporting(E_ERROR);
require_once './includes/bootstrap.inc';
drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);

function load_person_nodes() {
  $results = db_query('select nid
                       from node
                       where type="person"');
  $people = array();
  while ($result = db_fetch_object($results)) {
    $people[$result->nid] = node_load($result->nid);
  }
  return $people;
}

function add_new_node($netid) {
  $node = new StdClass();
  $node->uid = 1;
  $node->type = 'person';
  $node->status = 1; // published
  $node->promote = 0; // don't promote to front page
  $node->format=2; // full HTML
  $node->body = ''; // add later
  $node->path = 'person/' . $netid; // ?q=path
  $node->field_netid[0]['value'] = $netid;
  node_save($node);
}

function update_library($node, $library_nid) {
 $node->field_library[0]['nid'] = $library_nid;
 node_save($node);
}

function update_department($node, $depart_name, $depart_tid) {
  $tax = new StdClass();
  $tax->vid = $vid;
  $tax->tid = $depart_tid;
  $tax->name = $depart_name;
  $tax->weight = 0;
  if (! isset($node->taxonomy)) {
    $node->taxonomy = array();
  }
  $node->taxonomy[$depart_tid] = $tax;
  //print_r($node->taxonomy);
  node_save($node);
}

function get_ldap_data2($return_fields=NULL, $netid=NULL) {
  echo "netid: " . $netid . "\n";
  if ($netid == NULL) {
    $netid = cu_authenticate();
  }
  $output = NULL;

  if ($return_fields == NULL) {
    $return_fields = array('eduPersonPrimaryAffiliation',
                           'cornellEduAcadCollege',
                           'givenName',
                           'sn',
                           'cornellEduCampusAddress',
                           'cornellEduCampusPhone',
                           'Mail',
                         );
  } else if (is_string($return_fields)) {
    $return_fields = split(',', $return_fields);
  }

  if ($ds=ldap_connect("directory.cornell.edu")) {
    echo "got connection \n";
    $r=ldap_bind($ds);
    $sr=ldap_search($ds,"ou=People,o=Cornell University,c=US", "uid=$netid", $return_fields);

    if ($entries = ldap_get_entries($ds, $sr)) {
      echo "got entries \n";
      $output = array();
      for ($i=0; $i < count($return_fields); $i++) {
        $attr_name = $entries[0][$i];
        if ($attr_name != '') {
          $value = $entries[0][$attr_name][0];
          $output[$attr_name] = $value;
        }
      }
    }

    ldap_close($ds);
  } else {
    echo "Could not connect to LDAP server. \n";
    watchdog('cul_common (LDAP data)', 'Could not connect to LDAP server', array(), WATGHDOG_ERROR);
  }
  return $output;
}

function update_from_ldap($node, $fn, $ln, $add, $phone, $email) {
  echo "title should be: " . $fn . ' ' . $ln . "\n";
  $node->title = $fn . ' ' . $ln;
  $node->field_firstname[0]['value'] = $fn;
  $node->field_lastname[0]['value'] = $ln;
  $node->field_work_address[0]['value'] = $add;
  $node->field_person_phone[0]['value'] = $phone;
  $node->field_person_email[0]['email'] = $email;
  node_save($node);
}

// ______________________________________________________
// call each of these in turn

function assign_existing_netids($people) {
  foreach ($people as $node) {
    if (! isset($node->field_netid[0]['value'])) {
      echo 'updating: ' . $node->nid . "\n";
      if (isset($node->field_person_email[0]['email'])) {
        $email_parts = split('@', $node->field_person_email[0]['email']);
        $netid = $email_parts[0];
        $node->field_netid[0]['value'] = $netid;
        node_save($node);
      } else {
        echo 'email was not set for: ' . $node->nid . "\n";
      }
    }
  }
}

function add_all_nodes($people, $new_netids) {
  $netids = array();
  foreach ($people as $node) {
    if (isset($node->field_netid[0]['value']) && $node->field_netid[0]['value'] != '') {
      //echo 'got this netid: ' . $node->field_netid[0]['value']  . "\n";
      $netids[] = $node->field_netid[0]['value'];
    }
  }

  foreach ($new_netids as $newid) {
    if (! in_array($newid, $netids)) {
      echo 'adding: ' . $newid . "\n";
      add_new_node($newid);
    }
  }
}

function add_libraries($people, $netids_to_library, $libraries) {
  foreach ($people as $node) {
    if (isset($node->field_netid[0]['value']) && $node->field_netid[0]['value'] != '') {
      $library = $netids_to_library[$node->field_netid[0]['value']];
      $library_nid = $libraries[$library];
      //echo 'library nid: ' . $library_nid . "\n";
      //echo 'library name: ' . $library . "\n";
      update_library($node, $library_nid);
    }
  }
}

function add_depts($people, $netids_to_dept, $depts) {
  foreach ($people as $node) {
    if (isset($node->field_netid[0]['value']) && $node->field_netid[0]['value'] != '') {
      $dept_name = $netids_to_dept[$node->field_netid[0]['value']];
      $depart_tid = $depts[$dept_name.trim()];
      //echo 'dept tid: ' . $depart_tid . "\n";
      //echo 'dept name: ' . $dept_name . "\n";
      update_department($node, $depart_name, $depart_tid);
    }
  }
}

function add_ldap_data($people) {
  foreach ($people as $node) {
    if (isset($node->field_netid[0]['value']) && $node->field_netid[0]['value'] != '') {
      echo 'querying for: ' . $node->field_netid[0]['value'] . "\n";
      $ldap = get_ldap_data2('givenname,sn,cornelleducampusaddress,cornelleducampusphone,mail' ,$node->field_netid[0]['value']);
      //print_r($ldap);
      update_from_ldap($node, $ldap['givenname'], $ldap['sn'], $ldap['cornelleducampusaddress'], $ldap['cornelleducampusphone'], $ldap['mail']);
    }
  }
}

function display_nodes($people) {
  foreach ($people as $node) {
    echo 'NETID: ' . $node->field_netid[0]['value'] . "\n";
    echo 'TITLE: ' . $node->title = $firstname . ' ' . $lastname . "\n";
    echo 'FIRSTNAME: ' . $node->field_firstname[0]['value'] . "\n";
    echo 'LASTNAME: ' . $node->field_lastname[0]['value'] . "\n";
    echo 'WORKADDRESS: ' . $node->field_work_address[0]['value'] . "\n";
    echo 'PHONE: ' . $node->field_person_phone[0]['value'] . "\n";
    echo 'EMAIL: ' . $node->field_person_email[0]['email'] . "\n";
    echo 'LIBRARY: ' . $node->field_library[0]['nid'] . "\n";
    print_r($node->taxonomy);
    echo "\n\n";
  }
}

$people = load_person_nodes();
assign_existing_netids($people);
add_all_nodes($people, $new_netids);
// add_libraries($people, $netids_to_library, $libraries);
// add_depts($people, $netids_to_dept, $depts);
// add_ldap_data($people);

// reload people and double-check
$people = load_person_nodes();
display_nodes($people);
?>
